apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftyuweaq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftyuweaq
  template:
    metadata:
      labels:
        app: ftyuweaq
    spec:
      containers:
      - image: okteto.dev/ftyuweaq:latest
        name: ftyuweaq
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirr.umd.edu"
        - name: Vless_UUID
          value: "ccd3ede0-c665-4122-bb88-ee3cfa1225cf"
        - name: Vless_Path
          value: "/233"
        - name: Vmess_UUID
          value: "ccd3ede0-c665-4122-bb88-ee3cfa1225cf"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
